[package]
name = "infra-aws"
version = "0.0.0"
edition = "2021"
rust-version = "1.63"

[dependencies]
avalanche-sdk = { version = "0.0.21", features = ["cloudwatch"] } # https://crates.io/crates/avalanche-sdk
avalanche-types = { version = "0.0.27", features = [] }
aws-manager = "0.0.14"
compress-manager = "0.0.2"
log = "0.4.17"
random-manager = "0.0.1"
tokio = { version = "1.20.1", features = ["full"] } # https://github.com/tokio-rs/tokio/releases

[dev-dependencies]
cmp-manager = "0.0.1"
env_logger = "0.9.0"
tokio-test = "0.4.2"
