[package]
name = "blizzard-aws"
version = "0.0.0"
edition = "2021"
rust-version = "1.64"

[[bin]]
name = "blizzard-aws"
path = "src/main.rs"

[dependencies]
avalanche-sdk = { version = "0.74.0" } # https://crates.io/crates/avalanche-sdk
avalanche-types = { version = "0.0.74" } # https://crates.io/crates/avalanche-types
aws-manager = "0.19.2" # https://github.com/gyuho/aws-manager/tags
aws-sdk-cloudwatch = "0.19.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-ec2 = "0.19.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-s3 = "0.19.0" # https://github.com/awslabs/aws-sdk-rust/releases
blizzardup-aws = { path = "../../bin/blizzardup-aws" }
clap = { version = "4.0.11", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
env_logger = "0.9.1"
ethers = "0.17.0"
log = "0.4.17"
random-manager = "0.0.1"
tokio = { version = "1.21.2", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
