[package]
name = "avalanche-kms"
version = "0.2.43" # https://github.com/ava-labs/avalanche-ops/releases
edition = "2021"
rust-version = "1.67"

[dependencies]
avalanche-types = { version = "0.0.241", features = ["jsonrpc_client", "wallet", "wallet_evm", "kms_aws", "utils"] } # https://crates.io/crates/avalanche-types
aws-manager = { version = "0.24.6", features = ["kms", "sts"] } # https://github.com/gyuho/aws-manager/tags
clap = { version = "4.1.4", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
crossterm = "0.26.0"
dialoguer = "0.10.3"
env_logger = "0.10.0"
ethers-signers = "1.0.2"
id-manager = "0.0.2"
log = "0.4.17"
primitive-types = "0.12.1" # https://crates.io/crates/primitive-types
tokio = { version = "1.25.0", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
