[package]
name = "blizzardup-aws"
version = "0.2.26" # https://github.com/ava-labs/avalanche-ops/releases
edition = "2021"
rust-version = "1.66"

[[bin]]
name = "blizzardup-aws"
path = "src/main.rs"

[dependencies]
avalanche-types = { version = "0.0.187", features = ["avalanchego", "subnet_evm"] } # https://crates.io/crates/avalanche-types
aws-manager = { version = "0.22.19", features = ["cloudformation", "cloudwatch", "ec2", "s3", "sts"] } # https://github.com/gyuho/aws-manager/tags
aws-sdk-cloudformation = "0.22.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-ec2 = "0.22.0" # https://github.com/awslabs/aws-sdk-rust/releases
aws-sdk-s3 = "0.22.0" # https://github.com/awslabs/aws-sdk-rust/releases
clap = { version = "4.0.32", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
compress-manager = "0.0.4"
crossterm = "0.25.0"
dialoguer = "0.10.2"
dir-manager = "0.0.1"
env_logger = "0.10.0"
http-manager = "0.0.6"
id-manager = "0.0.2"
lazy_static = "1.4.0"
log = "0.4.17"
prometheus-manager = "0.0.21"
random-manager = "0.0.2"
regex = "1.7.0"
rust-embed = "6.4.2"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.16" # https://github.com/dtolnay/serde-yaml/releases
signal-hook = "0.3.14"
tokio = { version = "1.23.0", features = ["full"] } # https://github.com/tokio-rs/tokio/releases

[dev-dependencies]
tempfile = "3.3.0"
