[package]
name = "coreth"
version = "0.0.1"
edition = "2021"

[dependencies]
log = "0.4.17"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"

[dev-dependencies]
env_logger = "0.9.0"
