[package]
name = "avalanchego"
version = "0.0.1"
edition = "2021"

[dependencies]
avalanche-types = { path = "../avalanche-types" }
log = "0.4.16"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.80"
utils = { path = "../utils" }

[dev-dependencies]
env_logger = "0.9.0"
num-bigint = "0.4.3"
rust-embed = "6.4.0"
tempfile = "3.3.0"
