[package]
name = "staking-key-cert-s3-downloader"
version = "0.1.2"
edition = "2021"
rust-version = "1.62"

[dependencies]
aws-manager = "0.0.12"
clap = { version = "3.2.16", features = ["cargo", "derive"] } # https://github.com/clap-rs/clap/releases
env_logger = "0.9.0"
infra-aws = { path = "../../infra-aws" }
log = "0.4.17"
tokio = { version = "1.20.1", features = ["full"] } # https://github.com/tokio-rs/tokio/releases
