[package]
name = "certs-manager"
version = "0.0.0"
edition = "2021"
rust-version = "1.64"

[dependencies]
avalanche-types = { version = "0.0.74" } # https://crates.io/crates/avalanche-types
aws-manager = "0.19.2" # https://github.com/gyuho/aws-manager/tags
log = "0.4.17"
tokio = { version = "1.21.2", features = ["full"] } # https://github.com/tokio-rs/tokio/releases

[dev-dependencies]
cmp-manager = "0.0.1"
env_logger = "0.9.1"
random-manager = "0.0.1"
tokio-test = "0.4.2"
